### ISSUE TITLE
offline mods

### ISSUE THREAD

**Issue by switchdo** [viktorholk/arma3-mod-manager-cli#3]
Is there a way to load my offline mods?

**Comment by viktorholk** [comment]
Are you referring to "custom" mods outside of Steam workshop?

It loads all the mods from the YOUR_NAME/Library/Application\ Support/Steam/steamapps/workshop/content/107410

it should be possibly to add a custom mod to the folder. The mod folder needs to be a number tho since it expects a mod ID when loading

**Comment by switchdo** [comment]
Yes, my own mods that I am testing. Ok, so I should move them to the workshop folder and rename them. Thanks

**Comment by viktorholk** [comment]
If that doesn't work let me know.

In a future release I will add the possibility to add custom mods, without adding them manually to the workshop folder
